name: Zombienet Integration Tests

on:
  workflow_dispatch:
    inputs:
      parachain_tag:
        description: 'Release tag version for astar collator'
        required: true
        default: '1.0.0'
      polkadot_tag:
        description: 'Release tag version for polkadot relay chain'
        required: true
        default: '1.1.0'
      zombienet_tag:
        description: 'Release tag version for zombinet tool'
        required: true
        default: '1.3.37'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
    - run: mkdir -p integration-tests/bin

    - name: Download pre-built linux collator binary
      run: |
        wget https://github.com/djuromatic/para-ext/releases/download/v${{ github.event.inputs.parachain_tag }}/para-ext-v${{ github.event.inputs.parachain_tag }}-ubuntu-x86_64.tar.gz
        tar -xvf para-ext-*-ubuntu-x86_64.tar.gz
        chmod +x ./para-ext
        mv para-ext integration-tests/bin/para-ext

    - name: Copy polkadot relay chain binary
      run: |
        wget https://github.com/paritytech/polkadot/releases/download/v${{ github.event.inputs.polkadot_tag }}/polkadot
        chmod +x ./polkadot
        mv polkadot integration-tests/bin/polkadot

    - name: Copy zombinet testing binary
      run: |
        wget https://github.com/paritytech/zombienet/releases/download/v${{ github.event.inputs.zombienet_tag }}/zombienet-linux-x64
        chmod +x ./zombienet-linux-x64
        mv zombienet-linux-x64 integration-tests/bin/zombienet-linux-x64

    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Install yarn
      run: |
        npm install -g yarn
        yarn install
      working-directory: ./integration-tests

    - name: Run tests
      run: yarn test
      working-directory: ./integration-tests
